### ISSUE TITLE
Deploy to production 

### ISSUE THREAD

**Issue by Sakrecoer** [alephium/new-wiki#11]
- [x] Proof read. Make sure content is clean and ready.
- [ ] Craft a little announcement and warn about potential broken links.

**Comment by nop33** [comment]
The site was deployed after https://github.com/alephium/new-wiki/pull/14 was merged

**Comment by Sakrecoer** [comment]
Since we took care of the redirects, i'm not sure we need to make an anonouncement. But it's potentially good content idea to remind people that they can send pull requests to it and that we reward that type of work.

Off to walk the dog now, but will finish drafting that here later:
https://docs.google.com/document/d/1SmfPX5XwcKK_iKdJZchhrOiIAzXmbvSFHkThvJ5rnwk/edit

**Comment by Sakrecoer** [comment]
Closing the issue since it's primary objective is accomplished :tada:

**Comment by nop33** [comment]
I think we can just include this as a section of our Wednesday announcement of the new releases.
